services:
  # PHP Application
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mapit_php_prod
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./storage:/var/www/html/storage
      - ./storage/logs:/var/www/html/logs
      - ./.env:/var/www/html/.env
    networks:
      - prod_network
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: mapit_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./storage/logs/nginx:/var/log/nginx
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/nginx/ssl:ro
    networks:
      - prod_network
    depends_on:
      - php
    restart: unless-stopped
    command: >
      sh -c "
        echo 'server {
            listen 80;
            server_name mapitedu.nl www.mapitedu.nl;
            root /var/www/html/public;
            index index.php index.html;
            
            # Security headers
            add_header X-Content-Type-Options nosniff;
            add_header X-Frame-Options DENY;
            add_header X-XSS-Protection \"1; mode=block\";
            add_header Referrer-Policy \"strict-origin-when-cross-origin\";
            
            # PHP handling
            location / {
                try_files \$$uri \$$uri/ /index.php?\$$query_string;
            }
            
            location ~ \.php\$$ {
                fastcgi_pass php:9000;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME /var/www/html/public\$$fastcgi_script_name;
                fastcgi_param PATH_INFO \$$fastcgi_path_info;
                fastcgi_read_timeout 300;
                fastcgi_buffer_size 128k;
                fastcgi_buffers 4 256k;
                fastcgi_busy_buffers_size 256k;
            }
            
            # Security - deny access to hidden files
            location ~ /\. {
                deny all;
            }
            
            # Static files
            location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2|ttf|eot|svg)\$$ {
                expires 1y;
                add_header Cache-Control \"public, immutable\";
            }
            
            # Let'\''s Encrypt
            location /.well-known/acme-challenge/ {
                root /var/www/certbot;
            }
        }' > /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'"

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mapit_mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: mapit_production
      MYSQL_USER: mapit_prod_user
      MYSQL_PASSWORD: prod_db_password_456
      TZ: Europe/Amsterdam
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prod_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mapit_redis_prod
    volumes:
      - redis_data:/data
    networks:
      - prod_network
    restart: unless-stopped

  # Let's Encrypt Certbot
  certbot:
    image: certbot/certbot:latest
    container_name: mapit_certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    command: >-
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email admin@mapitedu.nl
      --agree-tos
      --no-eff-email
      --force-renewal
      -d mapitedu.nl
      -d www.mapitedu.nl
    depends_on:
      - nginx

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  certbot_www:
    driver: local
  certbot_conf:
    driver: local

networks:
  prod_network:
    driver: bridge
    name: mapit_prod_network
