name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

    - name: Test SSH connection
      run: |
        echo "🔐 Testing SSH connection to ${{ secrets.PRODUCTION_HOST }}..."
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }} "echo 'SSH connection successful'"

    - name: Check server configuration
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }} "
          echo '🔍 Server configuration check:'
          echo '   OS Info:' && uname -a
          echo '   Docker version:' && docker --version
          echo '   Docker Compose version:' && docker compose version
          
          echo '🔥 UFW firewall status:'
          sudo ufw status || echo 'UFW not available'
          
          echo '🌐 Network interface status:'
          ip addr show | grep -E 'inet.*global' || echo 'Could not get network info'
          
          echo '📂 Checking deployment directory:'
          ls -la /opt/mapit/ || echo 'Directory not found'
        "    - name: Create deployment directory
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }} "
          sudo mkdir -p /opt/mapit/current
          sudo mkdir -p /opt/mapit/current/storage/logs
          sudo mkdir -p /opt/mapit/current/storage/uploads
          sudo mkdir -p /opt/mapit/current/docker/production/ssl
          sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /opt/mapit
        "

    - name: Copy application files
      run: |
        rsync -avz --delete \
          -e 'ssh -o StrictHostKeyChecking=no' \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='vendor' \
          --exclude='.env' \
          --exclude='storage/logs' \
          ./ ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }}:/opt/mapit/current/

    - name: Create production environment file
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }} "
          cat > /opt/mapit/current/.env << 'EOF'
        # Production Environment Configuration
        APP_ENV=production
        APP_DEBUG=false
        APP_NAME=\"MapIt - Travel Destination Mapping\"
        APP_URL=https://mapitedu.nl

        # Database Configuration
        DB_CONNECTION=mysql
        DB_HOST=mysql
        DB_PORT=3306
        DB_DATABASE=mapit_production
        DB_USERNAME=mapit_prod_user
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}

        # Session Configuration
        SESSION_DRIVER=redis
        SESSION_LIFETIME=1440

        # Mail Configuration
        MAIL_DRIVER=smtp
        MAIL_HOST=${{ secrets.MAIL_HOST || 'localhost' }}
        MAIL_PORT=${{ secrets.MAIL_PORT || '587' }}
        MAIL_USERNAME=${{ secrets.MAIL_USERNAME || '' }}
        MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD || '' }}
        MAIL_ENCRYPTION=tls

        # API Keys
        GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
        WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY || '' }}

        # Security
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}

        # File Upload Settings
        MAX_UPLOAD_SIZE=10485760
        ALLOWED_IMAGE_TYPES=jpg,jpeg,png,webp

        # Cache Configuration
        CACHE_DRIVER=redis
        CACHE_PREFIX=mapit_prod_

        # Logging
        LOG_LEVEL=warning
        LOG_CHANNEL=daily

        # SSL Configuration
        SSL_ENABLED=true
        FORCE_HTTPS=true        # Performance
        OPCACHE_ENABLED=true
        REDIS_CACHE_TTL=3600

        # Admin Settings
        ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL || 'admin@mapitedu.nl' }}
        
        # Redis Configuration
        REDIS_HOST=redis
        REDIS_PORT=6379
        REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
        EOF
        "

    - name: Set permissions
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }} "
          sudo chown -R www-data:www-data /opt/mapit/current
          sudo chmod -R 755 /opt/mapit/current
          sudo chmod -R 775 /opt/mapit/current/storage
          sudo chmod -R 775 /opt/mapit/current/public
        "

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }} "
          cd /opt/mapit/current
          echo '🔧 Stopping any existing containers...'
          sudo docker compose -f docker-compose.production.yml down || true
          
          echo '🧹 Cleaning up old containers and images...'
          sudo docker container prune -f || true
          sudo docker image prune -f || true
          
          echo '🚀 Starting new containers...'
          sudo docker compose -f docker-compose.production.yml up -d --build
          
          echo '📋 Container status:'
          sudo docker compose -f docker-compose.production.yml ps
          
          echo '📝 Container logs (last 20 lines):'
          sudo docker compose -f docker-compose.production.yml logs --tail=20
        "

    - name: Wait for services and check status
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }} "
          echo '⏳ Waiting for services to start...'
          sleep 60
          
          echo '🔍 Final container status:'
          sudo docker compose -f /opt/mapit/current/docker-compose.production.yml ps
          
          echo '📊 Port bindings:'
          sudo docker port \$(sudo docker compose -f /opt/mapit/current/docker-compose.production.yml ps -q nginx) 2>/dev/null || echo 'Nginx container not found'
          
          echo '🌐 Testing local HTTP connectivity:'
          curl -I -m 10 http://localhost/ || echo 'Local HTTP test failed'
          
          echo '📝 Recent nginx logs:'
          sudo docker logs \$(sudo docker compose -f /opt/mapit/current/docker-compose.production.yml ps -q nginx) --tail 30 2>/dev/null || echo 'Could not get nginx logs'
        "    - name: Test HTTP connectivity
      run: |
        echo "Testing HTTP connectivity..."
        sleep 30
        if curl -f -s -m 10 http://${{ secrets.PRODUCTION_HOST }}/ > /dev/null; then
          echo "✅ HTTP site is accessible"
        else
          echo "❌ HTTP site is not accessible - checking logs..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }} "sudo docker logs mapit_nginx_prod --tail 20"
        fi

    - name: Setup SSL certificates
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PRODUCTION_HOST }} "
          cd /opt/mapit/current
          
          echo '🔍 Checking if domain points to this server...'
          SERVER_IP=\$(curl -s ifconfig.me)
          echo '   Server IP: '\$SERVER_IP
          
          # Test if the domain resolves to this server by checking HTTP access
          echo '🌐 Testing HTTP access to domain...'
          if curl -f -s -m 10 -H 'Host: mapitedu.nl' http://localhost/ > /dev/null; then
            echo '✅ Domain is accessible via HTTP, proceeding with SSL setup'
            
            # Create certbot webroot directory
            sudo mkdir -p /var/lib/docker/volumes/mapit_prod_network_certbot_www/_data
            sudo chmod 755 /var/lib/docker/volumes/mapit_prod_network_certbot_www/_data
            
            # Get SSL certificates using certbot
            echo '📋 Requesting SSL certificates...'
            sudo docker compose -f docker-compose.production.yml run --rm certbot
            
            # Check if certificates were created
            if sudo docker volume inspect mapit_prod_network_certbot_conf >/dev/null 2>&1; then
              echo '✅ SSL certificates obtained successfully'
              
              # Switch to HTTPS configuration
              echo '🔄 Switching to HTTPS configuration...'
              sudo docker cp docker/production/nginx/https.conf mapit_nginx_prod:/etc/nginx/conf.d/default.conf
              
              # Test nginx configuration
              if sudo docker exec mapit_nginx_prod nginx -t; then
                # Reload nginx with HTTPS config
                sudo docker exec mapit_nginx_prod nginx -s reload
                echo '🚀 HTTPS is now active!'
                echo '📍 Your site is available at: https://mapitedu.nl'
              else
                echo '❌ HTTPS configuration test failed, staying with HTTP'
              fi
            else
              echo '⚠️ SSL certificate setup failed, continuing with HTTP'
            fi
          else
            echo '⚠️ Domain HTTP test failed. This could mean:'
            echo '   1. DNS is not pointing to this server yet'
            echo '   2. HTTP site is not accessible'
            echo '   Please check DNS settings and try again'
            echo '   For now, continuing with HTTP only'
          fi
        "

    - name: Health Check
      run: |
        echo "Waiting for application to be ready..."
        sleep 60
        for i in {1..10}; do
          if curl -f -s http://${{ secrets.PRODUCTION_HOST }}/health; then
            echo "✅ Health check passed"
            exit 0
          fi
          echo "⏳ Waiting for application... (attempt $i/10)"
          sleep 15
        done
        echo "❌ Health check failed, but deployment may still be successful"
        echo "Check manually at http://${{ secrets.PRODUCTION_HOST }}"

    - name: Deployment Summary
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "🚀 Deployment completed!"
          echo "📍 Your site should be available at: http://${{ secrets.PRODUCTION_HOST }}"
          echo "🔍 Health check: http://${{ secrets.PRODUCTION_HOST }}/health"
        else
          echo "❌ Deployment had issues. Check the logs above."
        fi
